spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: root
    password: 88888888
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
minio:
 endpoint: http://192.168.1.7:9000
 accesskey: ucApJg1LsjQYf8ew3Xb8
 secretkey: Am0ndBAUTRc9PhQF4vgDWfBuXVCzFzPRi9luuiU6
 expirationtime: 86400     #Expiration time in seconds - 60 * 60 * 24

